### ISSUE TITLE
ERR unable to install app with gzip error="archive/tar: invalid tar header"

### ISSUE THREAD

**Issue by patsevanton** [devops-works/binenv#109]
Hello! Thanks for binenv!

Try add fselect
```
  fselect:
    description: Find files with SQL-like queries
    list:
      type: github-releases
      url: https://api.github.com/repos/jhspetersson/fselect/releases
    fetch:
      url: https://github.com/jhspetersson/fselect/releases/download/{{ .Version }}/fselect-x86_64-linux-musl.gz
    install:
      type: tgz
      binaries:
        - fselect
```
