### ISSUE TITLE
Multiple binaries can be specified, but only the latest is installed

### ISSUE THREAD

**Issue by leucos** [devops-works/binenv#198]
Example for docker-slim.

This spec installs both binaries but `docker-slim-sensor` will be installed at `~/.binenv/binaries/docker-slim/X.Y.Z`.

```
    install:
      type: tgz
      binaries:
        - docker-slim
        - docker-slim-sensor
```

Another argument (see #171) to change binaries layout from `binaries/DIST/VERSION` to `binaries/DIST/VERSION/BINARYNAME`
