### ISSUE TITLE
Add checksum validation of downloaded archives

### ISSUE THREAD

**Issue by ppetr** [devops-works/binenv#205]
While downloading from GitHub via HTTPS gives a reasonable level of security, I'd still prefer to have the binaries verified against their respective checksum files.

I propose to add a field with a URL to a checksum file together with a checksum of the file itself. Example:

```yaml
  foo_binary:
    fetch:
      url: https://github.com/...
    checksums:
      type: sha256  # Hash type used in checksums.txt as well as in `hash` below.
      url: https://github.com/foo/bar/releases/.../checksums.txt
      hash: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

After downloading an archive for `foo_binary`, `binenv` would also download the `checksums.txt` file, verify its integrity, and then verify the integrity of the archive against the appropriate checksum in `checksums.txt`.

An alternative would be to include all the hashes in `distributions.yaml` itself, but I think it'd be way too verbose.

I'm happy to contribute a PR once an agreement is reached on the details.

**Comment by leucos** [comment]
Hello @ppetr

That would be great.

However I've left this aside for now because I fear there will be a lot of nitty gritty details (checksums for compressed binaries, checksums inside tarballs, non standard checksum file formats, ...).

If you want to tackle this please go ahead. The above proposal seems fine to me. Keep us informed !

**Comment by ppetr** [comment]
Great! Let's keep it simple, just to verify checksums of tarballs as they're already provided. Later we can think of expanding it, if needed.

I'll then start working on a prototype and I'll keep you updated 🙂.

**Comment by ppetr** [comment]
After some experimenting I came to the following ideas, which can be implemented relatively independently.

**Provide a checksum of a checksum file for each released version.** This is the simplest solution and probably easiest to work with for authors/maintainers, but it's a bit more verbose in the distribution file.

```yaml
fzf:
  description: fzf is a general-purpose command-line fuzzy finder.
  url: https://github.com/junegunn/fzf/
  list:
    type: github-releases
    url: https://api.github.com/repos/junegunn/fzf/releases
  fetch:
    url: https://github.com/junegunn/fzf/releases/download/{{ .Version }}/fzf-{{ .Version }}-{{ .OS }}_{{ .Arch }}.tar.gz
  integrity:
    url: https://github.com/junegunn/fzf/releases/download/{{ .Version }}/fzf_{{ .Version }}_checksums.txt
    checksums:
      - url: https://github.com/junegunn/fzf/releases/download/0.30.0/fzf_0.30.0_checksums.txt
        type: sha256
        checksum: 43cc37783e0bf4ed775109379b3e2073ea2bb29c9e4811d07907c868435e1b7e
      # Other versions follow.
  install:
    type: tgz
    binaries:
      - fzf
```

**Use OpenPGP to sign chechsum files.** This is often done by authors that already use PGP.

A random example: https://github.com/orgrim/pg_back/releases/tag/v2.1.0. The release includes the `checksums.txt` and its signature `checksums.txt.asc`. Then it'd be enough to provide the public key(s) of the author(s) once and use it to verify any of their releases:

```yaml
  integrity:
    url: https://github.com/junegunn/fzf/releases/download/{{ .Version }}/fzf_{{ .Version }}_checksums.txt.sig
    public_key:
      # This would require https://gopenpgp.org/, probably a more heavy-weight library.
      openpgp:
        - |
          -----BEGIN PGP PUBLIC KEY BLOCK -----
          ...
```
