### ISSUE TITLE
add kubeconform

### ISSUE THREAD

**Issue by axgkl** [devops-works/binenv#263]
https://github.com/yannh/kubeconform

in use e.g. by flux a lot, e.g https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh

With this I could get to a working `binenv install kubeconform 0.6.7` :

```yaml
  kubeconform:
    description: >
      Kubeconform is a Kubernetes manifest validation tool. Incorporate it into your CI, or use it locally to validate your Kubernetes configuration!
    url: https://github.com/yannh/kubeconform/
    list:
      type: github-releases
      url: https://api.github.com/repos/yannh/kubeconform/releases
    fetch:
      url: https://github.com/yannh/kubeconform/releases/download/v{{ .Version }}/kubeconform-{{ .OS }}-{{ .Arch }}.tar.gz
    install:
      type: tgz
      binaries:
        - kubeconform
```

but w/o that version binenv reported "unable to select latest stable version for \"kubeconform\": no stable version available" - not sure what's missing.
