### ISSUE TITLE
add hetzner-k3s

### ISSUE THREAD

**Issue by axgkl** [devops-works/binenv#264]
hi again, 

since binenv already has a few hetzner specific tools, I think this one is a good fit. 
installs k3s into hetzner infra, easier and faster than e.g. terraform:

```yaml
  hetzner-k3s:
    description: The easiest and fastest way to create production grade Kubernetes clusters in Hetzner Cloud
    url: https://github.com/vitobotta/hetzner-k3s
    list:
      type: github-releases
      url: https://api.github.com/repos/vitobotta/hetzner-k3s/releases
    fetch:
      url: https://github.com/vitobotta/hetzner-k3s/releases/download/v{{ .Version }}/hetzner-k3s-{{ .OS }}-{{ .Arch }}
    install:
      type: direct

```
